name: Run tests and publish on new tag

on:
    - push
    - pull_request

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    - windows-latest
                    - ubuntu-latest
                    - macos-latest

        name: Test on ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v2
              with:
                  node-version-file: '.nvmrc'

            - name: Get npm cache directory
              id: npm-cache-dir
              run: echo "::set-output name=dir::$(npm config get cache)"

            - uses: actions/cache@v2
              id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
              with:
                  path: ${{ steps.npm-cache-dir.outputs.dir }}
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - run: npm ci

            - name: Setup python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.x

            - run: python3 -m pip install virtualenv

            - name: Run tests on headless linux using xvfb
              run: xvfb-run -a npm test
              if: runner.os == 'Linux'

            - name: run tests on windows/mac
              run: npm test
              if: runner.os != 'Linux'

            - name: Publish to extension marketplace when new tag is pushed
              if: matrix.os == 'ubuntu-latest' && startswith(github.ref, 'refs/tags/v')
              run: npm run deploy
              env:
                  VSCE_PAT: ${{ secrets.VSCE_PAT }}
